
import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';
import type { Opportunity } from '@/types/admin';
import type { OpportunityStatusType } from '@/constants/opportunityStatuses';

export const useOpportunityEditor = (opportunityId?: string | null) => {
  const { user } = useAuth();
  const [opportunity, setOpportunity] = useState<Opportunity | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    if (opportunityId && user) {
      fetchOpportunity();
    } else if (!opportunityId && user) {
      // Create new opportunity template
      setOpportunity({
        id: '', // Will be generated by database
        opportunity_id: '',
        name: '',
        theme_id: 'default',
        company_name: '',
        contact_person: '',
        target_role: '',
        notes: '',
        status: 'unpublished', // Default status for new opportunities
        user_id: user.id,
        is_passcode_protected: false,
        access_passcode: '',
        intro_video_url_en: '',
        intro_video_url_sv: ''
      });
    }
  }, [opportunityId, user]);

  const fetchOpportunity = async () => {
    if (!opportunityId || !user) return;
    
    setLoading(true);
    setError(null);
    
    try {
      const { data, error: fetchError } = await supabase
        .from('opportunities')
        .select('*')
        .eq('opportunity_id', opportunityId)
        .eq('user_id', user.id)
        .single();

      if (fetchError) {
        throw fetchError;
      }

      // Ensure status is properly typed and mapped from legacy values
      let validStatus: OpportunityStatusType = 'unpublished';
      
      if (data.status === 'unpublished' || data.status === 'published' || data.status === 'archived') {
        validStatus = data.status as OpportunityStatusType;
      } else if (data.status === 'active') {
        validStatus = 'published';
      } else if (data.status === 'paused') {
        validStatus = 'unpublished';
      } else if (data.status === 'closed') {
        validStatus = 'archived';
      }

      setOpportunity({
        ...data,
        status: validStatus,
        is_passcode_protected: data.is_passcode_protected || false,
        access_passcode: data.access_passcode || '',
        intro_video_url_en: data.intro_video_url_en || '',
        intro_video_url_sv: data.intro_video_url_sv || '',
        user_id: user.id // Ensure user_id is always set
      });
    } catch (err) {
      console.error('Error fetching opportunity:', err);
      setError(err instanceof Error ? err.message : 'Failed to fetch opportunity');
    } finally {
      setLoading(false);
    }
  };

  const updateOpportunity = (updates: Partial<Opportunity>) => {
    if (!opportunity) return;
    setOpportunity({ ...opportunity, ...updates });
  };

  const saveOpportunity = async (): Promise<boolean> => {
    if (!opportunity || !user) {
      console.error('Save failed: Missing opportunity or user');
      toast({
        title: "Error",
        description: "Missing opportunity data or user authentication",
        variant: "destructive"
      });
      return false;
    }

    console.log('=== SAVE OPPORTUNITY START ===');
    console.log('Opportunity database ID:', opportunity.id);
    console.log('OpportunityId parameter:', opportunityId);
    console.log('User ID:', user.id);
    console.log('Opportunity data:', {
      name: opportunity.name,
      opportunity_id: opportunity.opportunity_id,
      is_passcode_protected: opportunity.is_passcode_protected,
      access_passcode: opportunity.access_passcode,
      status: opportunity.status
    });

    // Validate required fields
    if (!opportunity.name || !opportunity.opportunity_id) {
      console.error('Save failed: Missing required fields');
      toast({
        title: "Error",
        description: "Please fill in all required fields (Name, Opportunity ID)",
        variant: "destructive"
      });
      return false;
    }

    // Validate status is one of the allowed values
    const allowedStatuses = ['unpublished', 'published', 'archived'];
    if (!allowedStatuses.includes(opportunity.status)) {
      console.error('Save failed: Invalid status value:', opportunity.status);
      toast({
        title: "Error",
        description: "Invalid status value. Please select a valid status.",
        variant: "destructive"
      });
      return false;
    }

    setIsSaving(true);
    try {
      // Prepare update data with explicit field mapping
      const updateData: any = {
        name: opportunity.name.trim(),
        opportunity_id: opportunity.opportunity_id.trim(),
        theme_id: opportunity.theme_id,
        company_name: opportunity.company_name?.trim() || null,
        contact_person: opportunity.contact_person?.trim() || null,
        target_role: opportunity.target_role?.trim() || null,
        notes: opportunity.notes?.trim() || null,
        status: opportunity.status,
        is_passcode_protected: Boolean(opportunity.is_passcode_protected),
        intro_video_url_en: opportunity.intro_video_url_en?.trim() || null,
        intro_video_url_sv: opportunity.intro_video_url_sv?.trim() || null,
        updated_at: new Date().toISOString()
      };

      // Handle passcode field explicitly
      if (opportunity.is_passcode_protected) {
        updateData.access_passcode = opportunity.access_passcode?.trim() || '';
      } else {
        updateData.access_passcode = null;
      }

      console.log('Update data prepared:', updateData);

      if (opportunity.id && opportunity.id !== '') {
        // Update existing opportunity using database ID only
        console.log('Updating existing opportunity using database ID:', opportunity.id);
        const { error: updateError } = await supabase
          .from('opportunities')
          .update(updateData)
          .eq('id', opportunity.id); // Only use database ID for updates

        if (updateError) {
          console.error('Update error details:', updateError);
          throw updateError;
        }
        console.log('Update successful');
      } else {
        // Create new opportunity
        const insertData = {
          ...updateData,
          user_id: user.id
        };

        console.log('Creating new opportunity...');
        const { data: insertedData, error: insertError } = await supabase
          .from('opportunities')
          .insert(insertData)
          .select()
          .single();

        if (insertError) {
          console.error('Insert error details:', insertError);
          throw insertError;
        }
        
        // Update the opportunity state with the new database ID
        if (insertedData) {
          setOpportunity(prev => prev ? { ...prev, id: insertedData.id } : null);
        }
        console.log('Insert successful');
      }

      console.log('=== SAVE OPPORTUNITY SUCCESS ===');
      toast({
        title: "Success",
        description: `Opportunity ${opportunity.id ? 'updated' : 'created'} successfully`,
        variant: "default"
      });

      return true;
    } catch (err) {
      console.error('=== SAVE OPPORTUNITY ERROR ===');
      console.error('Error details:', err);
      console.error('Error message:', err instanceof Error ? err.message : 'Unknown error');
      console.error('Error code:', (err as any)?.code);
      console.error('Error details:', (err as any)?.details);
      
      let errorMessage = 'Failed to save opportunity';
      if (err instanceof Error) {
        errorMessage = err.message;
        
        // Handle specific database constraint errors
        if (err.message.includes('duplicate key')) {
          errorMessage = 'An opportunity with this ID already exists';
        } else if (err.message.includes('violates check constraint')) {
          if (err.message.includes('opportunities_status_check')) {
            errorMessage = 'Invalid status value. Please select a valid status from the dropdown.';
          } else {
            errorMessage = 'Invalid data format. Please check your inputs';
          }
        } else if (err.message.includes('permission denied')) {
          errorMessage = 'You do not have permission to save this opportunity';
        }
      }
      
      toast({
        title: "Error",
        description: errorMessage,
        variant: "destructive"
      });
      return false;
    } finally {
      setIsSaving(false);
    }
  };

  return {
    opportunity,
    loading,
    error,
    updateOpportunity,
    saveOpportunity,
    isSaving
  };
};
