
import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';

interface Theme {
  id?: string;
  theme_id: string;
  name: string;
  browser_title?: string;
  branding?: any;
  content?: any;
  danibot?: any;
  user_id?: string;
}

export const useThemeEditor = (themeId?: string | null) => {
  const { user } = useAuth();
  const [theme, setTheme] = useState<Theme | null>(null);
  const [originalThemeId, setOriginalThemeId] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    if (themeId && user) {
      fetchTheme();
    } else if (!themeId && user) {
      // Create new theme template
      setTheme({
        id: '', // Will be generated by database
        theme_id: '',
        name: '',
        browser_title: '',
        user_id: user.id,
        branding: {
          primaryColor: 'blue-600',
          secondaryColor: 'purple-600',
          accentColor: 'pink-600',
          gradients: {
            hero: 'from-blue-50 via-purple-50 to-pink-50',
            primary: 'from-blue-600 to-purple-600',
            secondary: 'from-purple-600 to-pink-600'
          }
        },
        content: {
          targetRole: 'Customer Success Specialist',
          industry: 'Technology',
          companySpecificSkills: [],
          showHeroCTAs: true
        },
        danibot: {
          personality: 'professional',
          knowledgeBase: 'general',
          customGreeting: 'Hello! 👋 I\'m DaniBot, Daniel\'s personal AI assistant.'
        }
      });
    }
  }, [themeId, user]);

  const fetchTheme = async () => {
    if (!themeId || !user) return;
    
    setLoading(true);
    setError(null);
    
    try {
      const { data, error: fetchError } = await supabase
        .from('themes')
        .select('*')
        .eq('theme_id', themeId)
        .eq('user_id', user.id)
        .single();

      if (fetchError) {
        throw fetchError;
      }

      setTheme(data);
      setOriginalThemeId(data.theme_id); // Store original theme_id for comparison
    } catch (err) {
      console.error('Error fetching theme:', err);
      setError(err instanceof Error ? err.message : 'Failed to fetch theme');
    } finally {
      setLoading(false);
    }
  };

  const updateTheme = (updates: Partial<Theme>) => {
    if (!theme) return;
    setTheme({ ...theme, ...updates });
  };

  const updateTranslationsThemeId = async (oldThemeId: string, newThemeId: string): Promise<void> => {
    if (!user) {
      throw new Error('User not authenticated');
    }

    console.log(`Migrating translations from ${oldThemeId} to ${newThemeId} for user ${user.id}`);

    const { error } = await supabase
      .from('translations')
      .update({ theme_id: newThemeId })
      .eq('theme_id', oldThemeId)
      .eq('user_id', user.id);

    if (error) {
      console.error('Translation migration error:', error);
      throw new Error(`Failed to migrate translations: ${error.message}`);
    }

    console.log('Translation migration successful');
  };

  const saveTheme = async (): Promise<boolean> => {
    if (!theme || !user) {
      console.error('Save failed: Missing theme or user');
      toast({
        title: "Error",
        description: "Missing theme data or user authentication",
        variant: "destructive"
      });
      return false;
    }

    console.log('=== SAVE THEME START ===');
    console.log('Theme database ID:', theme.id);
    console.log('ThemeId parameter:', themeId);
    console.log('User ID:', user.id);
    console.log('Theme data:', {
      name: theme.name,
      theme_id: theme.theme_id,
      browser_title: theme.browser_title
    });

    // Validate required fields
    if (!theme.name || !theme.theme_id) {
      console.error('Save failed: Missing required fields');
      toast({
        title: "Error",
        description: "Please fill in all required fields (Name, Theme ID)",
        variant: "destructive"
      });
      return false;
    }

    setIsSaving(true);
    try {
      // Check if theme_id has changed and migrate translations if needed
      const newThemeId = theme.theme_id.trim();
      const hasThemeIdChanged = originalThemeId && originalThemeId !== newThemeId && theme.id;
      
      if (hasThemeIdChanged) {
        console.log(`Theme ID changed from ${originalThemeId} to ${newThemeId}, migrating translations...`);
        toast({
          title: "Updating translations...",
          description: "Migrating translations to new theme ID",
        });
        
        await updateTranslationsThemeId(originalThemeId!, newThemeId);
        setOriginalThemeId(newThemeId); // Update the stored original theme_id
      }

      const updateData = {
        name: theme.name.trim(),
        theme_id: newThemeId,
        browser_title: theme.browser_title?.trim() || null,
        branding: theme.branding,
        content: theme.content,
        danibot: theme.danibot,
        updated_at: new Date().toISOString()
      };

      console.log('Update data prepared:', updateData);

      if (theme.id && theme.id !== '') {
        // Update existing theme using database ID
        console.log('Updating existing theme using database ID:', theme.id);
        const { error: updateError } = await supabase
          .from('themes')
          .update(updateData)
          .eq('id', theme.id)
          .eq('user_id', user.id);

        if (updateError) {
          console.error('Update error details:', updateError);
          throw updateError;
        }
        console.log('Update successful');
      } else {
        // Create new theme
        const insertData = {
          ...updateData,
          user_id: user.id
        };

        console.log('Creating new theme...');
        const { data: insertedData, error: insertError } = await supabase
          .from('themes')
          .insert(insertData)
          .select()
          .single();

        if (insertError) {
          console.error('Insert error details:', insertError);
          throw insertError;
        }

        // Update the theme state with the new database ID
        if (insertedData) {
          setTheme(prev => prev ? { ...prev, id: insertedData.id } : null);
        }
        console.log('Insert successful');
      }

      console.log('=== SAVE THEME SUCCESS ===');
      toast({
        title: "Success",
        description: `Theme ${theme.id ? 'updated' : 'created'} successfully`,
      });

      return true;
    } catch (err) {
      console.error('=== SAVE THEME ERROR ===');
      console.error('Error details:', err);
      console.error('Error message:', err instanceof Error ? err.message : 'Unknown error');
      console.error('Error code:', (err as any)?.code);
      console.error('Error details:', (err as any)?.details);
      
      let errorMessage = 'Failed to save theme';
      if (err instanceof Error) {
        errorMessage = err.message;
        
        // Handle specific database constraint errors
        if (err.message.includes('duplicate key')) {
          errorMessage = 'A theme with this ID already exists';
        } else if (err.message.includes('violates check constraint')) {
          errorMessage = 'Invalid data format. Please check your inputs';
        } else if (err.message.includes('permission denied')) {
          errorMessage = 'You do not have permission to save this theme';
        }
      }
      
      toast({
        title: "Error",
        description: errorMessage,
        variant: "destructive"
      });
      return false;
    } finally {
      setIsSaving(false);
    }
  };

  return {
    theme,
    loading,
    error,
    updateTheme,
    saveTheme,
    isSaving
  };
};
