
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { crossDomainStorage } from '@/utils/crossDomainStorage';

const SUPABASE_URL = "https://unkrkwebogmyyxnwnfdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVua3Jrd2Vib2dteXl4bnduZmRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Nzk3NDksImV4cCI6MjA2NDI1NTc0OX0.WRDo7rU6ujIsvCJIFrrbPFriyZExtMWbdN4csTaGomA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: crossDomainStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});
